# Generated by Django 4.2.2 on 2023-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_1',
            field=models.FileField(max_length=250, upload_to='NEW/'),
        ),
    ]
